languageCode = "en"
languageName = "English"
weight = 1
title = "Umifish"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/yhtumr_logo.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Umiri"
  email = "nuno@n9o.xyz"
  image = "img/yhtumr_logo.png"
  headline = "Umiri 的 Blowfish 博客。"
  bio = "A powerful, lightweight theme for Hugo."
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]