languageCode = "zh-cn"
languageName = "简体中文"
weight = 9
title = "河豚博客"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/blowfish_logo_transparent.png"
  description = "一个强大、轻量级的 Hugo 主题。"

[params.author]
  name = "无密栗"
  email = "nuno@n9o.xyz"
  image = "img/yhtumr_logo.png"
  headline = "无密栗的河豚博客。"
  bio = "A powerful, lightweight theme for Hugo."
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]