# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters
# 你现在看到的是：umiri-blog/config/_default/params.toml
# Hugo 会优先遵循这里的配置，而不是themes/blowfish/config/_default/params.toml 中的配置。
# 你可以很明显地从 colorScheme 的值看出，这里的配置是优先的。

colorScheme = "blowfish" 
# valid options: blowfish、avocado、fire、ocean、
# forest、princess、neon、bloody、terminal、marvel、noir、
# autumn、congo、slate、github 和 one-light

defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableA11y = false # 无障碍切换按钮
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true

replyByEmail = false

mainSections = ["posts", "docs"]
# robots = ""

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
# backgroundImageWidth = 1200

defaultBackgroundImage = "/img/tkum_bg.jpeg"
defaultFeaturedImage = "/img/tkum_bg.jpeg"
defaultSocialImage = "/img/tkum_bg.jpeg"
hotlinkFeatureImage = true
# imagePosition = "100% 50%"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

#giteaDefaultServer = "https://git.fsfe.org"
#forgejoDefaultServer = "https://v11.next.forgejo.org"

fingerprintAlgorithm = "sha512" # Valid values are "sha512" (default), "sha384", "sha256"

[header]
  layout = "basic" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "custom" # valid options: page, profile, hero, card, background, custom
  homepageImage = "/img/tkum_bg.jpeg" # used in: hero, and card
  showRecent = true
  showRecentItems = 10
  showMoreLink = true
  showMoreLinkDest = "posts"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background
  disableHeroImageFilter = false # only used when layout equals hero

[article]
  showDate = true
  showViews = true
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = false
  # showAuthorBottom = ture
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/lignedefuite/"
  editAppendPath = true
  seriesOpened = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showAuthorsBadges = true
  showWordCount = false
  sharingLinks = [ "linkedin", "twitter", "bluesky", "reddit", "whatsapp", "telegram", "pinterest", "facebook", "email", "line"]
  showZenMode = true

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true 
  # only used when heroStyle equals background 
  # 向下滚动列表页时，是否模糊背景图。
  layoutBackgroundHeaderSpace = true # 在标题和正文之间添加空白区域间隔。
  showBreadcrumbs = false
  showSummary = true
  # 是否在列表页显示文章摘要。如果在扉页参数中没有提供摘要，
  # 那么将会使用站点配置 中的 summaryLength 参数自动生成一个。
  showViews = false
  showLikes = false
  showTableOfContents = true # 是否在文章中显示目录表。
  showCards = false # 是否将每个文章显示为卡片或简单的内联文本。
  orderByWeight = true
  groupByYear = true # 是否根据年做聚合。
  cardView = true
  cardViewScreenWidth = false # 增强列表中卡片的宽度，使其可以占据可用的全部宽度。
  constrainItemsWidth = true # 将项目宽度限制为 prose 以提高可读性。在没有 feature 图片的时候非常有用。

[sitemap]
  excludedKinds = []
  # 从生成的 /sitemap.xml 文件中排除的内容。 具体的配置请参考Hugo 文档。

[taxonomy] # 分类法 这里的设置会影响到/tags
  showTermCount = true # 是否在分类列表总显示对应的数量。
  showHero = true # 缩略图是否会在每个页面中作为 hero 图像显示。
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false # 是否在标题栏显示面包屑导航。
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term] # 术语
  showHero = false
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[firebase] # Firebase(Firebase 平台)
  apiKey = "AIzaSyB5tqlqDky77Vb4Tc4apiHV4hRZI18KGiY"
  authDomain = "blowfish-21fff.firebaseapp.com"
  projectId = "blowfish-21fff"
  storageBucket = "blowfish-21fff.appspot.com"
  messagingSenderId = "60108104191"
  appId = "1:60108104191:web:039842ebe1370698b487ca"
  measurementId = "G-PEDMYR1V0K"

[fathomAnalytics] # Fathom Analytics(一种网站分析工具)
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics] # Umami Analytics(一种网站分析工具)
  # websiteid = "ABC12345"
  # domain = "llama.yoursite.com"
  # dataDomains = "yoursite.com,yoursite2.com"
  # scriptName = ""
  # enableTrackEvent = false

[selineAnalytics]
  # token = "XXXXXX"
  # enableTrackEvent = false

# [buymeacoffee]
#   identifier = "nunocoracao"
#   globalWidget = true
#   globalWidgetMessage = ""
#   globalWidgetColor = "#FFDD00"
#   globalWidgetPosition = "right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[rssnext]
  # feedId = ""
  # userId = ""

[advertisement]
  # adsense = ""
